### ISSUE TITLE
[Suggestion] Option to offset camera

### ISSUE THREAD

**Issue by innj** [tr7zw/FirstPersonModel#109]
The entire player model sliding across the ground/vehicle as you rotate your camera is very weird to me. I tried disabling the offset and that would just obstruct the view below the camera. I am suggesting that an option to offset the camera instead of the entire model be added. A toggle may not even be needed, they might work somewhat okay together, who knows? Preferably an option to change the up/down offset as well as the forward/back offset, to make the camera better align with the head. It might cause issues with multiplayer servers, kind of like the player height option.

**Comment by tr7zw** [comment]
The offset sliders move the model relative to the camera, not the other way around. In the default settings the camera is already basically aligned with the head, because as you noticed setting everything to 0 just places it right above the neck(where it technically is located in mc's logic).
`It might cause issues with multiplayer servers, kind of like the player height option.` and that's one of the reason why it won't happen(Also probably would feel horrible to play when rotation the camera physically moves it(kinda like f5 but in first person), and would cause clipping into stuff when you are next to a wall). I still have to look more into how the sitting animated position is determined because especially with modded Chairs it doesn't work well currently (#77). When rotating the camera while standing still the player in fact kinda slides over the floor behind the camera(well that's also what happens in third-person or other players in multi-player), so maybe adding that at least the legs move a bit in https://github.com/tr7zw/NotEnoughAnimations could help to fix this.

**Comment by innj** [comment]
> The offset sliders move the model relative to the camera, not the other way around.
That's exactly what I'm suggesting?
> Also probably would feel horrible to play when rotation the camera physically moves it(kinda like f5 but in first person), and would cause clipping into stuff when you are next to a wall).
It doesn't have to be enabled by default.

**Comment by tr7zw** [comment]
`That's exactly what I'm suggesting?` you suggested moving the camera relative to the model, not the model to the camera.
The issue is I know exactly what a can of worms and issues this is to open.
`Then I don't understand why there's an option to change the camera height along with player height` I limited the height slider for that exact reason. If there where a slider to move the camera in the other directions you could just crank it up and have a build in range hack for pvp or can just look through walls by slamming your head into them. Ofc you could then try to limit the range back to the original camera position or move the camera visually but have the real camera back at it's original position but suddenly the block you are looking at is not correct anymore and then you start to be in the can of worms I mentioned. Also how do other mods react to that? This is also kinda the reason there are no other mods that physically move the camera away (except up/down, but that's kinda provided by mc itself) and at most tilt the camera.

**Comment by innj** [comment]
If there are issues with any offset other than the forward/back offset, simply don't implement those. I honestly don't see how the forward/back offset would be a problem though.

**Comment by tr7zw** [comment]
Like I said, it creates tons of issues and will probably make you motion sick in no time, added to that, that it's extremely unpractical for gameplay since everything is distorted(hit ranges/block you are looking at/rotating = moving/camera position != actual position/when sneaking on the edge of a block you fly even further away/jump'n'runs become harder since you have to jump after visually already off the block/and probably more). You can probably try to achieve this effect with some mod that allows you to reposition the camera in 3rd person like a shoulder surfing mod or so, but you will quickly see why 3rd person controls are not a good idea for first person.

**Comment by innj** [comment]
> Like I said, it creates tons of issues and will probably make you motion
sick in no time

That's the reason Minecraft now has options to scale distortion and FOV
effects.
> You can probably try to achieve this effect with some mod that allows you
to reposition the camera in 3rd person like a shoulder surfing mod or so,
but you will quickly see why 3rd person controls are not a good idea for
first person.

I could not find a Fabric mod that adds this behavior.

I wouldn't expect the feature to make most people motion sick, as it's how
turning your head works IRL. I can understand how it would, though.
I tested the Shoulder Surfing Reloaded mod with the camera placed right in
front of my head to mimic the requested feature, and while running around I
could not tell any difference most of the time.
