### ISSUE TITLE
Animation oversight

### ISSUE THREAD

**Issue by Kiriot22fet** [tr7zw/FirstPersonModel#136]
Soul torches have the default holding animation instead of having the same animation as the normal torches do.

**Comment by WolfieWaffle** [comment]
Would it be possible to use an item tag for items you hold in front of you, maybe a torch tag?
I have my own torch mod and a user is asking for my custom torches to be held out in first person, but it looks like that's from this mod.
If you just point me to the code that handles certain items being held in front, I could try a PR myself.

**Comment by tr7zw** [comment]
Oh this issue is on the wrong mod, so I forgot to close it. The item holding logic is in not enough animations and can be freely configured in the config file. https://github.com/tr7zw/NotEnoughAnimations/blob/1.17/NEAShared/src/main/java/dev/tr7zw/notenoughanimations/config/Config.java#L12 feel free to make a pr/open an issue with the item ids of the custom torches to be added there.

**Comment by WolfieWaffle** [comment]
thanks
