### ISSUE TITLE
[Bug] calling for wrong dependency 

### ISSUE THREAD

**Issue by SylisMC** [tr7zw/FirstPersonModel#221]
On curse forge, FirstPersonMod-2.0.2.jar(1.17+) calls for....

- TRansliterationLib-1.0.4.jar (1.16)
- NotEnoughAnimations-1.0.3.jar (1.16)

**Comment by SylisMC** [comment]
Update, i just noticed that FPM calls for NEA, and they might be responsible

**Comment by tr7zw** [comment]
Huh it downloaded the 1.16 dependencies for the 1.17 version?

**Comment by SylisMC** [comment]
yes, that is currently what it is doing, i tested it on a brand new pack,

**Comment by tr7zw** [comment]
Which launcher did you use? On Curse no versions are directly linked as dependency, but just projects. So the launcher has to pick the correct jar for Forge/Fabric and the MC version.

**Comment by SylisMC** [comment]
I am using the curse launcher. 

fabric-api-0.38.1+1.17.jar
FirstPersonMod-2.0.2.jar
NotEnoughAnimations-1.0.3.jar

Sorry for the lack of information at first... i assumed it was just a wrong dependency lable. Let me know if you need anything else from me,

**Comment by tr7zw** [comment]
Huh that's realllly odd. Why would it pull the 1.0.4 of TRansliterationLib when there's a full release for 1.17. 
I kinda suspected that the launcher downloaded the 1.16 version of Firstperson because the 1.17 is marked as a Beta, and that it loads the 1.16 dependencies because of that. 
I'll keep it in mind, I'm planing to release a new version in the next few days of Firstperson and Transliteration, maybe that will fix it.

**Comment by tr7zw** [comment]
This is now resolved. Curse supports selecting multiple modloaders now, perfectly when I'm more or less done making everything 2 jars instead 👀.
