### ISSUE TITLE
Helmet not hiding correctly

### ISSUE THREAD

**Issue by tr7zw** [tr7zw/FirstPersonModel#227]
Mods known to cause this issue:
- Minecraft Dungeons Armor

**Comment by Noaaan** [comment]
Hey, I have some more details regarding this issue, as more and more people are pointing it out.

I would recommend looking at https://github.com/ZsoltMolnarrr/BetterCombat/issues/27 for more examples/screenshots of what is happening here.

In my case for Mythic Metals, my armor uses Fabric API's `ArmorRenderer` to register custom meshes as BipedEntityModels. I believe due to that implementation the armor is rendered unexpectedly in quite a few scenarios.

From reading some of the srouce code, this is also what happens with [Aether Reborns Phoenix Armor](https://github.com/devs-immortal/Paradise-Lost/blob/3602d5034548661179053318a4cfedbd5475e866/src/main/java/net/id/aether/client/rendering/armor/PhoenixArmorRenderer.java)

Immersive Armor does something a bit worse, which is implementing their own [ArmorFeatureRenderer](https://github.com/Luke100000/ImmersiveArmors/blob/adcf0e95a998b59384e1c6402ff92ecea8d18432/common/src/main/java/immersive_armors/mixin/MixinArmorFeatureRenderer.java#L85)

Adding compatability for Fabric API would solve most of these cases. I think a potential solution would be considering writing a Mixin into it, or some other attempt to try culling/stop rendering the head layer while in first-person (this would have to happen late somewhere).

Hopefullly this sheds some light on the issue.

**Comment by tr7zw** [comment]
Yeah, I am in contact with the BetterCombat devs, and I am aware that my current workarounds don't fully work there. The next update will contain the Fabric API integration to hopefully better prevent them from rendering.

**Comment by tr7zw** [comment]
Fixed(my cancel point was set up in a stupid way, now it should catch all mod armor).
