### ISSUE TITLE
Crashes on startup, presumably because of something in main (Fabric)

### ISSUE THREAD

**Issue by Gavator234** [tr7zw/FirstPersonModel#243]
No other mods installed, crash log provides all other information.
[crash.txt](https://github.com/tr7zw/FirstPersonModel/files/7559796/crash.txt)

**Comment by tr7zw** [comment]
That looks like you have some kind of corrupted/broken jar? The stacktrace at least doesn't seem to match the codebase. Try redownloading version 2.0.1 or 2.0.2 from curse.

**Comment by Gavator234** [comment]
Trust me, I've tried redownloading and the older version. I honestly don't know what the issue could possibly be, because Minecraft works, fabric works, and all of the dependencies work.

**Comment by tr7zw** [comment]
https://github.com/tr7zw/FirstPersonModel/blob/1.16/Core/src/main/java/dev/tr7zw/firstperson/FirstPersonModelCore.java#L51 the crash above has a null pointer in that line. That is impossible since it's assigned one line above. And the lines above and below can't be null either. Maybe try to run the game in Java 16 so it can produce a more usable crashreport. Or try to reinstall fabric to check that the Fabric version is correct. But other than that, honestly, no clue how that crash could happen. I mean an alternative would be to just give the 1.17 version a try since you are using Fabric and 1.16 is just in maintenance mode.

**Comment by Gavator234** [comment]
I don't think using 1.17 would be a possibility (I'm trying to use a modpack) but I'll certainly try reinstalling fabric and updating Java whenever I can get back to my computer.

**Comment by tr7zw** [comment]
This is fabric, the modpack should have a 1.17 version, or alternative 1.17 modpacks with the same mods^^ I don't think any fabric mod that is active in any way is stuck on 1.16.

**Comment by Gavator234** [comment]
Here's after updating both fabric and Java to 1
[crash-2021-11-18_19.24.05-client.txt](https://github.com/tr7zw/FirstPersonModel/files/7567141/crash-2021-11-18_19.24.05-client.txt)
6

**Comment by tr7zw** [comment]
Ok that is in fact the old version from Feb 17th. This issue that I guess depends on something like the system lang? has been fixed on May 11th, and should be in the 2.0.2 build. On Curse that build is marked as an alpha cause it has some issue with Forge, but with Fabric it fixed this issue that only seems to be happening for a few people.

**Comment by Gavator234** [comment]
That's seems to have fixed it, thanks! Had to look for that build in the version specific spots though (on the right bar on Curse at the bottom), couldn't find it in the files tab.

**Comment by tr7zw** [comment]
![grafik](https://user-images.githubusercontent.com/5133936/142712205-df83b0d8-8266-40bf-bffb-7bbd440ebffe.png)
It's also in the files view ;)

**Comment by tr7zw** [comment]
Gonna mark it as Fabric only (because it somehow broke on Forge, but fixes bugs that can be important for fabric).
