### ISSUE TITLE
Sneaking in first person moves the body as little as it did pre Minecraft 1.14

### ISSUE THREAD

**Issue by AurelianCaesar** [tr7zw/FirstPersonModel#246]
Sneaking in first person incorrectly moves the body like it's pre 1.14.
![2022-01-04_05 57 07](https://user-images.githubusercontent.com/96740299/148011423-73dc4a16-2e0a-43d2-a50e-80ae23a87386.png)
![2022-01-04_05 56 24](https://user-images.githubusercontent.com/96740299/148011427-f506d2e8-c2ac-4058-9972-60b8f8666b80.png)
.

**Comment by tr7zw** [comment]
Like I mentioned on the curse comment, this is down to math. The camera is at a fixed position while rotating, but your head rotates at the neck, not the eyes. So either the camera would have to be pushed to the front and spin off-axes, or (like it's set up in this case) the body has to be pushed slightly behind the camera, so that when looking down you don't just look at the top of the torso/neck. This also has nothing to do with 1.14 and does affect all Minecraft versions ever released, if you were to make a first-person mod for them.

**Comment by AurelianCaesar** [comment]
This issue has nothing to do with my original comment on curseforge or the camera or whatever, look at my reply in curseforge for more info.

**Comment by tr7zw** [comment]
Not sure why the legs dont clip into the floor while in first person, because the y offset is unchanged(only x/z to correct for the camera rotation). Don't think this is an issue tho, since not clipping into the ground should be the normal behavior anyway?

**Comment by AurelianCaesar** [comment]
The problem is that the head still moves as far down as it does in vanilla which causes your shoulders to look weird, maybe I'm just nitpicking. If you feel like it I would be very happy if you added a new animation for sneaking in your notenoughanimations which is as tall as vanilla but doesn't clip into the ground.
