### ISSUE TITLE
problem when using the mod together with the Inmis Addon

### ISSUE THREAD

**Issue by peow** [tr7zw/FirstPersonModel#385]
the mod Inmis Addon places a 3d backpack on the player's back, and when used together with FirstPersonModel, when swimming downwards the backpack appears on the screen
![huge_2023-09-27_16 07 31](https://github.com/tr7zw/FirstPersonModel/assets/105888751/5cc3dbdf-250e-4846-9f6a-ac89903c7e32)
![huge_2023-09-27_22 40 43](https://github.com/tr7zw/FirstPersonModel/assets/105888751/30d725b7-7ea0-49e2-bd8e-6aac8fdb3002)

**Comment by 909oce** [comment]
i have the same issue, hoping to find some way to hide things like backpack in first person

**Comment by tr7zw** [comment]
This is one line to fix for them ( https://github.com/Globox1997/InmisAddon/blob/1.20/src/main/java/net/inmisaddon/util/BackpackUtil.java#L47 check here if the body is visible. If not, don't render the backpack too). I did add enhanced features to better hide stuff attached to the player, but since the backpack is just rendered in space without translating to the body/checking that the body is visible, there is nothing more I can directly do.

**Comment by tr7zw** [comment]
Just noticed that I already mentioned that over on the issue https://github.com/Globox1997/InmisAddon/issues/12 and it has been prioritized. Closing this issue here.
