### ISSUE TITLE
Request to add hidden models in Vanilla Hands mode

### ISSUE THREAD

**Issue by sfgd147** [tr7zw/FirstPersonModel#408]
When I use the Vanilla Hands mode with the 'Yes Steve Model' MOD, double arms appear on the screen. So please add the hidden model option when using Vanilla Hands mode.
![20240108072607](https://github.com/tr7zw/FirstPersonModel/assets/145850121/eab257c8-6038-43b4-9a22-5c0132cf6d2d)

**Comment by tr7zw** [comment]
> add the hidden model option

I don't know what you mean. During vanilla hands it doesn't interrupt the vanilla logic. So the code runs as normal. Thats the entire point of the setting. https://github.com/tr7zw/FirstPersonModel/blob/6ea849a837d498de839de623babfd99c0f53d568/Shared/src/main/java/dev/tr7zw/firstperson/mixins/HeldItemRendererMixin.java#L36 
Looks more like an issue between whatever added that gun and Yes Steve Model. Try pressing F6.

**Comment by sfgd147** [comment]
Well,The 'Yes Steve Model' mod is a mod that modifies the original player model.It's not using the Vanilla model,So not just that gun,other useing vanilla hand mode items will also do the same.
![20240108074538](https://github.com/tr7zw/FirstPersonModel/assets/145850121/1f0eebe7-e580-4902-a73d-62e1c3a0ca9c)

**Comment by sfgd147** [comment]
Can you add a list of items that automatically switch to F6 mode? Just like "autoVanilla Hands"

**Comment by tr7zw** [comment]
Ah, I assumed the vanilla arm was your problem. Then the main issue is just that these mods right now are incompatible. I set the players arms invisible and the item they are holding during vanilla hands. Since the mod replaces the vanilla model and doesn't seem to care about its settings, it doesn't work.

**Comment by tr7zw** [comment]
> Can you add a list of items that automatically switch to F6 mode? Just like "autoVanilla Hands"

Just for the gun mods? Not really planned rn.

**Comment by sfgd147** [comment]
> > Can you add a list of items that automatically switch to F6 mode? Just like "autoVanilla Hands"
> 
> Just for the gun mods? Not really planned rn.

yes.So my idea is to add an option to switch F6 to the Vanilla Hands mode

**Comment by tr7zw** [comment]
Maybe some time later. So far this has been only a problem with MrCrayFish's Gun Mod and only for vanilla hands(which is already a hacky fallback, IMO vanilla hands shouldn't ever be used in the first place, rn mainly used to fix modded maps not being readable cause mod devs don't add 3rd person animations). And since I don't think gun mods add anything to mc really, this is rather low priority. Adding this just throws another kinda dumb workaround onto the pile.

**Comment by sfgd147** [comment]
Okay, thank you very much. By the way, this matter actually has nothing to do with MrCrayFish :)

**Comment by tr7zw** [comment]
It's just the gun mod I directly know about. As I said, I don't think gun mods make sense for mc, so I never looked much into it. But I know that there are other ones with like 100+ weapons that also don't work quite right in 3rd person.
