### ISSUE TITLE
Items disappear in hands

### ISSUE THREAD

**Issue by Sansthesk3let0n** [tr7zw/FirstPersonModel#481]
https://github.com/user-attachments/assets/7ded1e40-b1ad-4a63-944d-78b36065396b

Items disappear from hands after a short period of time.
Seemed to have started when installing 3d player models, I uninstalled it but the problem still persisted. Any idea what is going on?

**Comment by tr7zw** [comment]
Duplicate of https://github.com/tr7zw/FirstPersonModel/issues/481 and I haven't been able to reproduce this at all, and neither issue provides the Mc version or other mods.

**Comment by CharredKiwi** [comment]
Having the same issue, there are no compatibility issues with any other mod I have installed. I am able to reproduce the issue 100% of the time. Playing in 1.21.1

How to reproduce issue
Load into any world
Wait 20-30 seconds
Both offhand item and normal hand item disappear
Tools only return when used (sword, pickaxe, shield, etc.)

Issue only stopped when mod was uninstalled/deactivated

HOWEVER, I loaded this mod with its dependencies ONLY (Fabric API, Mod Menu, Not Enough Animations, and Text Placeholder API (required by Mod Menu)) and there was no item disappearing issue, so this mod causes an issue with another mod not named in its incompatible section. 

At this time, I am unsure what mod however I am now randomly dedicated to getting this mod working, (probably because of Skyrim modding lol) and will go one by one to figure out what mod creates this issue then report it here ASAP.

**Comment by Sansthesk3let0n** [comment]
This sounds precisely the same as the issue I am having, would it be helpful to share our modpacks so that we can narrow down the mods causing issues more easily, from there we can use a binary search to find the incompatible mod.

**Comment by Sansthesk3let0n** [comment]
I have found the incompatibility, it seems to be the newest version of YDM's Weapon Master. I have downgraded the version and the issue has stopped

**Comment by MawMatt** [comment]
> I have found the incompatibility, it seems to be the newest version of YDM's Weapon Master. I have downgraded the version and the issue has stopped

thank you so much!
