### ISSUE TITLE
Add a way to only render specific part of the body

### ISSUE THREAD

**Issue by stevefan1999-personal** [tr7zw/FirstPersonModel#503]
The problem of #485 is that this mod renders the player's global locomotion in the first-person camera, so that collides with the animation system of TacZ. This is evidenced by doing a reload and you can see that the reload animation overlaps. A good way to workaround this is to just disable the hand rendering, so it only shows the arm when you are controlling the gun.

**Comment by tr7zw** [comment]
Not sure why this needs another issue. This mod renders the player while in first person. That's the point of the mod. Not sure why that breaks the TacZ animation system, but that's an issue on their end. If you just want to see the normal vanilla view while holding the guns, add them to the autoToggleModItems config.

**Comment by stevefan1999-personal** [comment]
> Not sure why this needs another issue. This mod renders the player while in first person. That's the point of the mod. Not sure why that breaks the TacZ animation system, but that's an issue on their end. If you just want to see the normal vanilla view while holding the guns, add them to the autoToggleModItems config.

No, you got me wrong. What I want to emphasize is that we could just render the entire torso and disable the arm rendering instead to get around the "four arms" issue in TacZ. I've already enabled the autoVanillaHands for TacZ but it still looks like this:

https://github.com/user-attachments/assets/0cb04ccc-c57a-4f78-a071-6fe7032749a3

This is kind of annoying, so if we can just disable the arm rendering, then we just need to slightly tilt the first-person camera offset position forward to get to a point where the reload animation perfectly match.

**Comment by tr7zw** [comment]
Thats what vanilla hands does as seen on the other issue(disabling the player models arms):
![grafik](https://github.com/user-attachments/assets/bed842f2-59e9-4a3e-a7ce-bd79d6d190e1)

Possible it doesn't work for you since you are using 2 unsupported mods that are known to not be compatible with no plans to make them compatible (a custom player model from cpm or so, that's why the arms are still there, and a gun mod). Just remove Firstperson mod or add the guns to the autoToggleModItems config.
