### ISSUE TITLE
Appears to crash with newer versions of sodium

### ISSUE THREAD

**Issue by coderbot16** [tr7zw/FirstPersonModel#59]
I don't have all of the details since I'm reporting this on behalf of someone else, but it appears that this mod crashes with sodium.

```
java.lang.NullPointerException: Ticking player 	at de.tr7zw.firstperson.StaticMixinMethods.isThirdPerson(StaticMixinMethods.java:16) 	at net.minecraft.class_4184.handler$cmm000$CameraInject(class_4184.java:1032) 	at net.minecraft.class_4184.method_19333(class_4184.java) 	at net.minecraft.class_1657.handler$bnh000$tick(class_1657.java:5323)
```

**Comment by tr7zw** [comment]
I can look into it, but personally, mods that replace the render engine like Sodium and Canvas are currently not the top priority, but I'll get to them eventually.

**Comment by tr7zw** [comment]
As an update: Currently reworking the way the player render is triggered and switching over to the FabricAPI to do that. So as long as the FabricAPI works(in this case the post entity render event), it should work with modified render pipelines. Also just found out about Iris, so going to make sure it's compatible with Iris+Sodium since shaders are important and Optifine is a mess.

**Comment by tr7zw** [comment]
Tested with Sodium and Iris without any issues.
