### ISSUE TITLE
Flying Animation Doesn't Work

### ISSUE THREAD

**Issue by JeffAxe123** [tr7zw/FirstPersonModel#63]
When flying with an elytra, you become completely invisible. This does not effect crawling or swimming at all. My guess is the flying animation is hardcoded to 3rd person in vanilla.

**Comment by tr7zw** [comment]
No, I hardcoded it to hide the player to prevent clipping(since that's the only thing you could see anyway). if you press f5, during eltra flying/riptide your head is in front and everything is behind you. So there is nothing to see really. During swimming, you can see the arms, so that's why it's still enabled there.

**Comment by JeffAxe123** [comment]
Oh okay that makes sense, your right we wouldn't see much anyway
