### ISSUE TITLE
[Suggestion] seperate mod for cosmetics

### ISSUE THREAD

**Issue by RyanCR03** [tr7zw/FirstPersonModel#68]
I tried the first person mod out and I loved the 3d hat layer feature and the other cosmetic features but I didn't like how you needed the first person perspective for it... so I'm suggesting you do what you did with the not enough animations mod and create a separate mod for it. the first person mod has some of my favorite features that I've always wanted but I just didn't like the fact you needed the first person.

**Comment by tr7zw** [comment]
Technically you can disable the first-person part of the mod entirely, but yes I kinda plan to split up the mod more, since it's scope for a single mod got way too big. I will finish the not enough animations mod first(all requested features and forge), and then probably extract the cosmetics part into it's own mod. But since I'm new-ish to the Fabric+Forge modding and CurseForge, I'm still experimenting a bit with what approach to take in regards to:
 - One Mod=One Repo=One branch=One Jar/One Mod=2 Repos=2 Jars/One Mod=1 Repo=2 Jars?
 - Having one CurseForge page for Forge+Fabric or two if it's 2 Jars?
 - Create a wrapping code base so I can write/maintain everything once that runs on Fabric and Forge/Just maintain 2 implementations
 - If creating a wrapping code base, create that as a mod that I depend on, include it inside the mod or create a separated one for each mod?
 - What about dependencies like Cloth Config? I had to create a wrapper for it to be able to use it on Fabric and Forge with the same code base, fabric allows to just include the cloth config mod as lib, for forge you need to do hacky things. And do I want 2 copies of cloth config inside each even tiny mod?

Just some of the things that I'm currently thinking about. From a gut feeling I'd probably say: Each mod one repo with one branch, not sure about Forge+Fabric jars or separated(really need feedback there from end-users and mod-pack creators in regards on what is the most usable), and creating one external dependency library mod for my mods that handles all the Forge/Fabric/Cloth Config stuff, so I have to maintain only one code base for each mod.

**Comment by FewerFlaws** [comment]
The biggest consideration in whether to do separate mod pages for fabric/forge versions is whether the features will be different.  If you plan to make differences as minimal as possible then distribute both versions from the same page to make maintenance easier.  If you anticipate significant differences in the mod description then use separate pages for accuracy.  The biggest consideration here is whether your features are version dependant.  Forge lags way behind fabric in terms of the minecraft version.

**Comment by tr7zw** [comment]
I mean the features would be 1:1 the same all the time. And for when 1.17 releases and forge takes its time, it would be fabric only for that time.

**Comment by tr7zw** [comment]
Cosmetics are now located in https://github.com/tr7zw/Cosmetizer
