### ISSUE TITLE
Skin layers are quite visible up close.

### ISSUE THREAD

**Issue by FewerFlaws** [tr7zw/FirstPersonModel#70]
It might be worth it to add a pixel on the y axis to close individual layers.  Match it to the color of the pixel its connected to to blend it in.  Corners would be odd.  Averaging the color of both connected faces would be best.  Priority matching would probably be fine for most skins (match front before sides and sides before back).
![2021-01-08_17 57 08](https://user-images.githubusercontent.com/75643699/104080606-f4b42100-51dd-11eb-8517-4bd44d026d55.png)

**Comment by tr7zw** [comment]
I guess you're talking about the armor? The issue with the armor is that it doesn't have any faces on the inside, and even adding them would not give a texture there, and even the texture would break with resource packs. I only see two options to make the armor less stupid than it looks right now: 3d modeled armor(bedrock/dungeons like) or trying to apply the 3d-ification that is also done on the skin 2nd layer to make the armor have real depth(would probably break again on non 16x texture packs).

**Comment by kb01guy** [comment]
As you can see in the Following Screenshot the Bottom Layers actually exist, they are just in the Ground Block and therefore not visible. I agree, that its not needed to bled in some extra layers, but maybe in the future it could be possible to set a Feet-Height. 

In the Screenshot the bottom layer seems black, but thats caused by the shader and boots-enchantment.
![2021-04-20_14 37 10](https://user-images.githubusercontent.com/41644237/115397072-f4b4bb80-a1e5-11eb-9949-a4f3d200d7d2.png)

**Comment by tr7zw** [comment]
I can't quiet follow you what you mean? that the lower part of the boots/feet clip into the ground while sneaking is a normal vanilla issue that probably doesn't have a not odd looking fix?

**Comment by SleepyTonia** [comment]
I mean… Offsetting the player model by half a pixel on the y axis when one wears boots could look fine and solve this part of the issue. And since the armor model is hard-coded you could perhaps optionally inject your own shrunk variation, simply making the armor model tighter on the first person model.

**Comment by tr7zw** [comment]
This basically is now related to making 3d-skin-layers work with armor. So will be tracked over there.
