### ISSUE TITLE
Idea for a better settings button placement.

### ISSUE THREAD

**Issue by RDKRACZ** [tr7zw/FirstPersonModel#75]
Instead of adding this little button on the left of the options button can you consider resizing the bedrockify button to half of its size (if present) and displaying your own button on the left?
![Screen Capture_20210117113436](https://user-images.githubusercontent.com/43277609/104838221-c7403500-58b9-11eb-9519-e9dff59a0128.png)

**Comment by tr7zw** [comment]
Can't resize their button(at least not in a straightforward way), and the issue is that the options menu gets modified by a lot of mods(Optifine/Sodium/Canvas).  So no, probably not gonna move the button in there. If the cosmetics button happens to be in the way(for example in modpacks), the config file has a toggle to hide the button in general.
