### ISSUE TITLE
Ice and Fire dragon riding looks super wonky

### ISSUE THREAD

**Issue by egshels** [tr7zw/FirstPersonModel#76]
![image](https://user-images.githubusercontent.com/31183838/104910411-4768a800-5957-11eb-9ffa-b810c58b8409.png)
This is also visible in first person, and presumably to other players. 
Unrelated, but the player model is very jittery when turning in first person on a horse.

**Comment by tr7zw** [comment]
``Unrelated, but the player model is very jittery when turning in first person on a horse.``
I can look into that one. In regards to the dragon mod, I'm not 100% certain why it'd look like this in the third person. It looks like the mod might hide the real player and render a custom version of the player as part of the dragon model. Might take some time to look into it since currently some rewrites are being done. Is this with the current 2.0.0 builds?

**Comment by egshels** [comment]
This is on 2.0.0 Forge. It also shows in first person, with the players model duplicated in front of and below the camera

**Comment by egshels** [comment]
![image](https://user-images.githubusercontent.com/31183838/104985864-e46f2380-59df-11eb-99dc-866ce9adea37.png)
![image](https://user-images.githubusercontent.com/31183838/104985873-e9cc6e00-59df-11eb-9cad-69dc64bda94b.png)
It seems like this happens without your mod.. I'll open an issue in the Ice and Fire repo

**Comment by tr7zw** [comment]
Yea that's an odd issue. I guess it renders the 2nd player on the dragon and places the real player above to fake the 3rd person? Could probably be done better 😅.
