### ISSUE TITLE
Sitting on modded chairs breaks players offset unless facing south

### ISSUE THREAD

**Issue by egshels** [tr7zw/FirstPersonModel#77]
![image](https://user-images.githubusercontent.com/31183838/104991983-fc4da400-59ed-11eb-9d3c-e1be093dd2a0.png)
![image](https://user-images.githubusercontent.com/31183838/104992012-0ff90a80-59ee-11eb-9c0f-819b6d5f9fce.png)
![image](https://user-images.githubusercontent.com/31183838/104992033-21421700-59ee-11eb-8b23-d60b51d1ec79.png)
This happens for every modded seat.
I'm not sure if this is fixable without just redoing how offset works when sitting

**Comment by basbakker1912** [comment]
Easily fixable by removing the last else statement from the `public void updatePositionOffset(Entity player, Vec3 defValue)` function at the check for vehicles. 

Removing this makes the earlier defined `realYaw` value used instead of the riden vehicle, which for most modded seats doesn't change direction.

I have fixed this locally, just lacking permissions to create a pull request.

**Comment by tr7zw** [comment]
This has been resolved, together with other sitting rotation issues.
